const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {URL}=require('url');
const {openStore}=require('./lib/store');
const {openFiles}=require('./lib/files');
const {openMailer}=require('./lib/mailer');
const {openAI}=require('./lib/ai');

const PORT=Number(process.env.PORT||3000);
const NODE_ENV=process.env.NODE_ENV||'development';
const SECRET=process.env.CINESET_SECRET||'dev-only-change-this-secret';
const PLACEHOLDER_SECRETS=['dev-only-change-this-secret','dev-secret-change-me','change-this-in-production','replace-with-a-long-random-secret'];
if(NODE_ENV==='production'&&(!process.env.CINESET_SECRET||PLACEHOLDER_SECRETS.includes(SECRET)||SECRET.length<32)){console.error('CINESET_SECRET must be set to a random value of at least 32 characters in production. Generate one with: openssl rand -hex 32');process.exit(1);}
// Demo accounts are seeded only outside production unless explicitly enabled.
const DEMO=process.env.CINESET_SEED_DEMO?process.env.CINESET_SEED_DEMO==='true':NODE_ENV!=='production';
const DEMO_EMAIL=/@cineset\.local$/;
const VERSION=require('./package.json').version;
const MAX_UPLOAD=Number(process.env.MAX_UPLOAD_MB||500)*1024*1024;
const ROOT=__dirname;
const DB_DIR=path.resolve(process.env.DATA_DIR||path.join(ROOT,'data'));
const DB_PATH=path.join(DB_DIR,'db.json');
const UPLOADS=path.resolve(process.env.UPLOADS_DIR||path.join(ROOT,'uploads'));
const PUBLIC=path.join(ROOT,'public');
const APP_BASE_URL=(process.env.APP_BASE_URL||`http://localhost:${PORT}`).replace(/\/$/,'');
fs.mkdirSync(DB_DIR,{recursive:true}); fs.mkdirSync(UPLOADS,{recursive:true});

const empty={users:[],workspaces:[],projects:[],comments:[],versions:[],approvals:[],files:[],portfolio:[],invites:[],team:[],calendar:[],quotes:[],invoices:[],contracts:[],notifications:[],aiPlans:[]};
// Set up in main(): db/save come from the store (JSON file or PostgreSQL); files, mailer and ai from lib/.
let db,save,store,files,mailer,ai;

const now=()=>new Date().toISOString();
const id=(p)=>p+'_'+crypto.randomBytes(9).toString('hex');
const hash=(value,salt=crypto.randomBytes(16).toString('hex'))=>({salt,hash:crypto.scryptSync(value,salt,64).toString('hex')});
const verify=(value,user)=>{try{return crypto.timingSafeEqual(crypto.scryptSync(value,user.passwordSalt,64),Buffer.from(user.passwordHash,'hex'));}catch{return false;}};
const safeName=(s)=>String(s||'upload.bin').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,180)||'upload.bin';
const mime=(file)=>({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.mp4':'video/mp4','.webm':'video/webm','.mov':'video/quicktime','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.gif':'image/gif','.pdf':'application/pdf','.txt':'text/plain; charset=utf-8'}[path.extname(file).toLowerCase()]||'application/octet-stream');

function tokenFor(userId){const p=Buffer.from(JSON.stringify({u:userId,e:Date.now()+7*86400000})).toString('base64url');const s=crypto.createHmac('sha256',SECRET).update(p).digest('base64url');return p+'.'+s;}
function userFromReq(req){
  const raw=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('cineset_session=')); if(!raw)return null;
  const val=decodeURIComponent(raw.slice(raw.indexOf('=')+1)); const [p,s]=val.split('.'); if(!p||!s)return null;
  const expected=crypto.createHmac('sha256',SECRET).update(p).digest('base64url'); if(s.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(expected)))return null;
  try{const payload=JSON.parse(Buffer.from(p,'base64url').toString()); if(Date.now()>payload.e)return null; return db.users.find(x=>x.id===payload.u)||null;}catch{return null;}
}
function sessionCookie(userId){return `cineset_session=${encodeURIComponent(tokenFor(userId))}; HttpOnly; Path=/; SameSite=Lax; Max-Age=604800${NODE_ENV==='production'?'; Secure':''}`;}
function clearCookie(){return 'cineset_session=; HttpOnly; Path=/; SameSite=Lax; Max-Age=0';}
function json(res,status,obj,headers={}){const body=Buffer.from(JSON.stringify(obj));res.writeHead(status,{...securityHeaders(),'Content-Type':'application/json; charset=utf-8','Content-Length':body.length,'Cache-Control':'no-store',...headers});res.end(body);}
function text(res,status,body,headers={}){const b=Buffer.from(body);res.writeHead(status,{...securityHeaders(),'Content-Type':'text/plain; charset=utf-8','Content-Length':b.length,...headers});res.end(b);}
function readJson(req,limit=2*1024*1024){return new Promise((resolve,reject)=>{let size=0;const chunks=[];req.on('data',c=>{size+=c.length;if(size>limit){reject(Object.assign(new Error('Payload too large'),{status:413}));req.destroy();return;}chunks.push(c);});req.on('end',()=>{try{const raw=Buffer.concat(chunks).toString('utf8');resolve(raw?JSON.parse(raw):{});}catch{reject(Object.assign(new Error('Invalid JSON'),{status:400}));}});req.on('error',reject);});}
function auth(req,res){const u=userFromReq(req); if(!u){json(res,401,{error:'Unauthorized'});return null;} return u;}
function projectForUser(u,p){return !!p&&(u.role==='creator'?p.ownerId===u.id:p.clientId===u.id);}
function ownerProject(u,projectId){const p=db.projects.find(x=>x.id===projectId);return p&&u.role==='creator'&&p.ownerId===u.id?p:null;}
// Clients a creator may work with: invited team members, or clients already on one of their projects.
function creatorClientIds(u){const ids=new Set();for(const t of db.team)if(t.ownerId===u.id&&t.role==='client')ids.add(t.memberUserId);for(const q of db.projects)if(q.ownerId===u.id&&q.clientId)ids.add(q.clientId);return ids;}
function linkTargets(u,b){const projectId=b.projectId?String(b.projectId).trim():null;const project=projectId?ownerProject(u,projectId):null;if(projectId&&!project)return{error:'Project not found'};const clientId=b.clientId?String(b.clientId).trim():(project?.clientId||null);if(clientId&&!creatorClientIds(u).has(clientId))return{error:'Client not found. Invite them to your workspace first.'};if(project?.clientId&&clientId&&clientId!==project.clientId)return{error:'Client is not on this project'};return{projectId,clientId};}
function notify(userId,type,title,message,projectId=null){db.notifications.unshift({id:id('n'),userId,type,title,message,projectId,read:false,createdAt:now()});db.notifications=db.notifications.slice(0,500);emailUser(userId,`CINESET: ${title}`,`${message}\n\nOpen CINESET: ${APP_BASE_URL}/`);}
function emailUser(userId,subject,text){if(!mailer.enabled||process.env.EMAIL_NOTIFICATIONS==='false')return;const user=db.users.find(x=>x.id===userId);if(!user||DEMO_EMAIL.test(user.email))return;mailer.send({to:user.email,subject,text});}
// Per-user limit on AI requests, since each one costs money.
const aiUsage=new Map();
function aiAllowed(userId){const limit=Number(process.env.AI_REQUESTS_PER_HOUR||20);const t=Date.now();const a=(aiUsage.get(userId)||[]).filter(x=>t-x<3600000);if(a.length>=limit){aiUsage.set(userId,a);return false;}a.push(t);aiUsage.set(userId,a);return true;}
function seed(){if(!DEMO||db.users.length)return;const a=hash('Demo1234'),b=hash('Demo1234');db.users=[{id:'u_creator',email:'creator@cineset.local',name:'CINESET Studio',role:'creator',passwordSalt:a.salt,passwordHash:a.hash,createdAt:now()},{id:'u_client',email:'client@cineset.local',name:'Sarah Ahmed',role:'client',passwordSalt:b.salt,passwordHash:b.hash,createdAt:now()}];db.workspaces=[{id:'ws_demo',ownerId:'u_creator',name:'CINESET Studio',slug:'cineset-studio',createdAt:now()}];
 const p={id:'p_bmw',ownerId:'u_creator',clientId:'u_client',name:'BMW Campaign',type:'Commercial',status:'Reviewing',progress:78,createdAt:now()};db.projects=[p];
 ['Treatment','Storyboard','First Cut','Final Delivery'].forEach((stage,i)=>db.approvals.push({id:id('ap'),projectId:p.id,stage,status:i<2?'Approved':i===2?'Reviewing':'Pending',updatedAt:now()}));
 db.versions=[{id:id('ver'),projectId:p.id,label:'V1',status:'Superseded',note:'Initial edit',createdAt:now()},{id:id('ver'),projectId:p.id,label:'V2',status:'Reviewing',note:'Slower transition + tighter grade',createdAt:now()}];
 db.comments=[{id:id('com'),projectId:p.id,versionId:db.versions[1].id,timecode:17,text:'Make this transition a little slower.',authorId:'u_client',resolved:false,createdAt:now()},{id:id('com'),projectId:p.id,versionId:db.versions[1].id,timecode:34,text:'Love the framing. Keep this shot.',authorId:'u_client',resolved:true,createdAt:now()}];
 db.portfolio=[{id:id('port'),ownerId:'u_creator',title:'BMW Campaign',type:'Commercial',year:2026,description:'Automotive campaign with restrained camera movement and a cinematic finish.',coverColor:'midnight',public:true,createdAt:now()},{id:id('port'),ownerId:'u_creator',title:'Brand Film',type:'Brand Film',year:2026,description:'A visual story built around atmosphere, texture and human performance.',coverColor:'silver',public:true,createdAt:now()}];
 db.team=[{id:id('team'),ownerId:'u_creator',memberUserId:'u_client',role:'client',permissions:{projects:true,review:true,files:true,portfolio:false},createdAt:now()}];
 db.calendar=[{id:id('cal'),ownerId:'u_creator',projectId:p.id,title:'Shoot Day',date:'2026-09-20',time:'09:00',location:'Basra',notes:'Call time 08:30',createdAt:now()}];
 db.quotes=[{id:id('quo'),ownerId:'u_creator',projectId:p.id,clientId:'u_client',number:'Q-2026-001',status:'Draft',currency:'USD',items:[{description:'Production package',qty:1,unit:5000}],total:5000,createdAt:now()}];
 db.invoices=[{id:id('inv'),ownerId:'u_creator',projectId:p.id,clientId:'u_client',number:'INV-2026-001',status:'Pending',currency:'USD',total:2500,dueDate:'2026-10-01',createdAt:now()}];
 db.contracts=[{id:id('ctr'),ownerId:'u_creator',projectId:p.id,clientId:'u_client',title:'Production Agreement',status:'Pending Signature',content:'Production agreement placeholder',createdAt:now()}];
 notify('u_creator','system','Welcome to CINESET','Your workspace is ready.','p_bmw');
 save();}

const rate=new Map();
function rateLimit(req){const key=(req.socket.remoteAddress||'unknown')+'|'+(req.url||'');const t=Date.now();let a=rate.get(key)||[];a=a.filter(x=>t-x<60000);a.push(t);rate.set(key,a);return a.length<=120;}
function securityHeaders(){return {'X-Content-Type-Options':'nosniff','X-Frame-Options':'SAMEORIGIN','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; media-src 'self' blob:; img-src 'self' data: blob:; connect-src 'self'; frame-ancestors 'self'"};}

async function route(req,res){
  Object.assign(res.headers={},securityHeaders());
  if(!rateLimit(req))return json(res,429,{error:'Too many requests'});
  const u=userFromReq(req); const parsed=new URL(req.url,'http://localhost'); const p=parsed.pathname; const method=req.method;
  if(method==='GET'&&p==='/api/health')return json(res,200,{ok:true,service:'CINESET',version:VERSION,env:NODE_ENV,demo:DEMO,integrations:{database:store.kind,storage:files.kind,email:mailer.enabled,ai:ai.kind}});
  if(method==='GET'&&p==='/api/auth/me')return u?json(res,200,{user:publicUser(u)}):json(res,401,{error:'Unauthorized'});
  if(method==='POST'&&p==='/api/auth/login'){try{const b=await readJson(req);const email=String(b.email||'').trim().toLowerCase();const user=db.users.find(x=>x.email.toLowerCase()===email);if(!user||(!DEMO&&DEMO_EMAIL.test(user.email))||!verify(String(b.password||''),user))return json(res,401,{error:'Invalid email or password'});return json(res,200,{user:publicUser(user)},{'Set-Cookie':sessionCookie(user.id)});}catch(e){return json(res,e.status||400,{error:e.message});}}
  if(method==='POST'&&p==='/api/auth/logout')return json(res,200,{ok:true},{'Set-Cookie':clearCookie()});
  if(method==='POST'&&p==='/api/auth/register'){try{const b=await readJson(req);const email=String(b.email||'').trim().toLowerCase();const name=String(b.name||'').trim();const password=String(b.password||'');if(!/^\S+@\S+\.\S+$/.test(email)||!name||password.length<8)return json(res,400,{error:'Name, valid email and password (8+ chars) are required'});if(db.users.some(x=>x.email===email))return json(res,409,{error:'Email already exists'});const h=hash(password);const user={id:id('user'),email,name,role:'creator',passwordSalt:h.salt,passwordHash:h.hash,createdAt:now()};db.users.push(user);db.workspaces.push({id:id('ws'),ownerId:user.id,name:name+' Workspace',slug:email.split('@')[0].replace(/[^a-z0-9-]/g,'-')+'-'+crypto.randomBytes(3).toString('hex'),createdAt:now()});save();return json(res,200,{user:publicUser(user)},{'Set-Cookie':sessionCookie(user.id)});}catch(e){return json(res,e.status||400,{error:e.message});}}

  if(method==='GET'&&p==='/api/projects'){if(!u)return json(res,401,{error:'Unauthorized'});return json(res,200,db.projects.filter(x=>projectForUser(u,x)));}
  if(method==='POST'&&p==='/api/projects'){if(!u||u.role!=='creator')return json(res,403,{error:'Creator only'});try{const b=await readJson(req);const clientEmail=String(b.clientEmail||'').trim().toLowerCase();let client=null;if(clientEmail){const allowed=creatorClientIds(u);client=db.users.find(x=>x.role==='client'&&x.email===clientEmail&&allowed.has(x.id));if(!client)return json(res,400,{error:'No client with that email in your workspace. Invite them first.'});}const project={id:id('proj'),ownerId:u.id,clientId:client?.id||null,name:String(b.name||'Untitled Project').trim().slice(0,120),type:String(b.type||'Commercial').slice(0,60),status:'Planning',progress:0,createdAt:now()};db.projects.push(project);['Treatment','Storyboard','First Cut','Final Delivery'].forEach((stage,i)=>db.approvals.push({id:id('ap'),projectId:project.id,stage,status:i===0?'Reviewing':'Pending',updatedAt:now()}));if(client)notify(client.id,'project','New project',`You were added to ${project.name}.`,project.id);save();return json(res,200,project);}catch(e){return json(res,e.status||400,{error:e.message});}}
  let m=p.match(/^\/api\/projects\/([^/]+)$/);
  if(method==='GET'&&m){if(!u)return json(res,401,{error:'Unauthorized'});const q=db.projects.find(x=>x.id===m[1]);if(!projectForUser(u,q))return json(res,404,{error:'Not found'});return json(res,200,{project:q,owner:db.users.find(x=>x.id===q.ownerId)?.name||'',client:q.clientId?db.users.find(x=>x.id===q.clientId)?.name||'':'',comments:db.comments.filter(x=>x.projectId===q.id).map(c=>({...c,authorName:db.users.find(z=>z.id===c.authorId)?.name||'User'})),versions:db.versions.filter(x=>x.projectId===q.id),approvals:db.approvals.filter(x=>x.projectId===q.id),files:db.files.filter(x=>x.projectId===q.id).map(f=>({id:f.id,originalName:f.originalName,mime:f.mime,size:f.size,createdAt:f.createdAt})),events:db.calendar.filter(x=>x.projectId===q.id),quotes:db.quotes.filter(x=>x.projectId===q.id),invoices:db.invoices.filter(x=>x.projectId===q.id),contracts:db.contracts.filter(x=>x.projectId===q.id)});}

  m=p.match(/^\/api\/projects\/([^/]+)\/comments$/);
  if(method==='POST'&&m){if(!u)return json(res,401,{error:'Unauthorized'});const q=db.projects.find(x=>x.id===m[1]);if(!projectForUser(u,q))return json(res,404,{error:'Not found'});try{const b=await readJson(req);const textVal=String(b.text||'').trim();if(!textVal)return json(res,400,{error:'Comment required'});const c={id:id('com'),projectId:q.id,versionId:b.versionId||null,timecode:Math.max(0,Number(b.timecode)||0),text:textVal.slice(0,2000),authorId:u.id,resolved:false,createdAt:now()};db.comments.push(c);notify(u.role==='creator'?q.clientId:q.ownerId,'comment','New feedback',`${u.name} added feedback on ${q.name}.`,q.id);save();return json(res,200,{...c,authorName:u.name});}catch(e){return json(res,e.status||400,{error:e.message});}}
  m=p.match(/^\/api\/comments\/([^/]+)$/);
  if(method==='PATCH'&&m){if(!u)return json(res,401,{error:'Unauthorized'});const c=db.comments.find(x=>x.id===m[1]),q=c&&db.projects.find(x=>x.id===c.projectId);if(!c||!projectForUser(u,q))return json(res,404,{error:'Not found'});const b=await readJson(req);c.resolved=!!b.resolved;save();return json(res,200,c);}
  m=p.match(/^\/api\/projects\/([^/]+)\/versions$/);
  if(method==='POST'&&m){if(!u||u.role!=='creator')return json(res,403,{error:'Creator only'});const q=ownerProject(u,m[1]);if(!q)return json(res,404,{error:'Not found'});const b=await readJson(req);db.versions.filter(x=>x.projectId===q.id&&x.status==='Reviewing').forEach(x=>x.status='Superseded');const v={id:id('ver'),projectId:q.id,label:String(b.label||`V${db.versions.filter(x=>x.projectId===q.id).length+1}`).slice(0,30),status:'Reviewing',note:String(b.note||'').slice(0,1000),createdAt:now()};db.versions.push(v);q.status='Reviewing';if(q.clientId)notify(q.clientId,'version','New version ready',`${v.label} is ready for review.`,q.id);save();return json(res,200,v);}
  m=p.match(/^\/api\/approvals\/([^/]+)$/);
  if(method==='PATCH'&&m){if(!u)return json(res,401,{error:'Unauthorized'});const a=db.approvals.find(x=>x.id===m[1]),q=a&&db.projects.find(x=>x.id===a.projectId);if(!a||!projectForUser(u,q))return json(res,404,{error:'Not found'});const b=await readJson(req);const allowed=u.role==='client'?['Approved','Changes Requested']:['Approved','Reviewing','Pending','Changes Requested'];if(!allowed.includes(b.status))return json(res,400,{error:'Invalid status'});a.status=b.status;a.updatedAt=now();if(a.status==='Approved'){const remain=db.approvals.filter(x=>x.projectId===q.id&&x.status!=='Approved').length;q.progress=Math.min(100,q.progress+25);q.status=remain===0?'Delivered':'Reviewing';}if(q.ownerId&&u.role==='client')notify(q.ownerId,'approval','Approval updated',`${u.name} updated ${a.stage} to ${a.status}.`,q.id);save();return json(res,200,a);}

  m=p.match(/^\/api\/projects\/([^/]+)\/files$/);
  if(method==='POST'&&m){if(!u)return json(res,401,{error:'Unauthorized'});const q=db.projects.find(x=>x.id===m[1]);if(!q||!projectForUser(u,q)||u.role!=='creator')return json(res,403,{error:'Creator only'});const filename=safeName(req.headers['x-filename']);const contentLength=Number(req.headers['content-length']||0);if(contentLength>MAX_UPLOAD)return json(res,413,{error:`File exceeds ${process.env.MAX_UPLOAD_MB||500} MB limit`});const stored=id('asset')+path.extname(filename);const target=path.join(UPLOADS,stored+'.part');let size=0;const out=fs.createWriteStream(target);let aborted=false;req.on('data',c=>{size+=c.length;if(size>MAX_UPLOAD&&!aborted){aborted=true;req.destroy(new Error('Too large'));try{fs.unlinkSync(target);}catch{}}});req.pipe(out);return await new Promise(resolve=>{out.on('finish',async()=>{if(aborted)return resolve();const type=req.headers['content-type']||mime(filename);try{await files.put(stored,target,type);}catch(e){try{fs.unlinkSync(target);}catch{};json(res,e.status||502,{error:e.message});return resolve();}const f={id:id('file'),projectId:q.id,ownerId:q.ownerId,uploadedBy:u.id,originalName:filename,storedName:stored,mime:type,size,createdAt:now()};db.files.push(f);if(q.clientId)notify(q.clientId,'file','New file',`${filename} was added to ${q.name}.`,q.id);save();json(res,200,{id:f.id,originalName:f.originalName,mime:f.mime,size:f.size});resolve();});out.on('error',e=>{try{fs.unlinkSync(target);}catch{};json(res,500,{error:e.message});resolve();});});}
  m=p.match(/^\/api\/files\/([^/]+)$/);
  if(method==='GET'&&m){if(!u)return json(res,401,{error:'Unauthorized'});const f=db.files.find(x=>x.id===m[1]),q=f&&db.projects.find(x=>x.id===f.projectId);if(!f||!projectForUser(u,q))return json(res,404,{error:'Not found'});const size=Number(f.size)||0;let start=0,end=size-1,status=200;const range=/bytes=(\d+)-(\d*)/.exec(req.headers.range||'');if(range){start=Number(range[1]);end=range[2]?Math.min(Number(range[2]),size-1):size-1;if(start>=size||start>end){res.writeHead(416,{...securityHeaders(),'Content-Range':`bytes */${size}`});return res.end();}status=206;}const headers={...securityHeaders(),'Content-Type':f.mime,'Accept-Ranges':'bytes','Content-Length':size?end-start+1:0,'Content-Disposition':`inline; filename="${f.originalName.replace(/"/g,'')}"`};if(status===206)headers['Content-Range']=`bytes ${start}-${end}/${size}`;if(!size){res.writeHead(200,headers);return res.end();}let stream;try{stream=await files.read(f.storedName,start,end);}catch(e){return json(res,e.status||502,{error:e.message});}res.writeHead(status,headers);stream.on('error',()=>res.destroy());return stream.pipe(res);}

  if(method==='GET'&&p==='/api/clients'){if(!u||u.role!=='creator')return json(res,403,{error:'Creator only'});const allowed=creatorClientIds(u);return json(res,200,db.users.filter(x=>x.role==='client'&&allowed.has(x.id)).map(c=>({id:c.id,name:c.name,email:c.email,projects:db.projects.filter(q=>q.ownerId===u.id&&q.clientId===c.id).length})));}
  if(method==='POST'&&p==='/api/invites'){if(!u||u.role!=='creator')return json(res,403,{error:'Creator only'});try{const b=await readJson(req);const email=String(b.email||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return json(res,400,{error:'Valid email required'});const invite={id:id('invite'),ownerId:u.id,email,token:crypto.randomBytes(24).toString('hex'),expiresAt:Date.now()+7*86400000,createdAt:now()};db.invites.push(invite);save();const inviteUrl=`/invite/${invite.token}`;const emailed=mailer.enabled&&await mailer.send({to:email,subject:`${u.name} invited you to CINESET`,text:`${u.name} invited you to their CINESET production workspace.\n\nAccept the invite: ${APP_BASE_URL}${inviteUrl}\n\nThis link expires in 7 days.`});return json(res,200,{inviteUrl,expiresAt:invite.expiresAt,emailed});}catch(e){return json(res,e.status||400,{error:e.message});}}
  m=p.match(/^\/api\/invites\/([^/]+)$/); if(method==='GET'&&m){const inv=db.invites.find(x=>x.token===m[1]);if(!inv||inv.acceptedAt||Date.now()>inv.expiresAt)return json(res,404,{error:'Invite invalid or expired'});return json(res,200,{email:inv.email,expiresAt:inv.expiresAt,existing:db.users.some(x=>x.email===inv.email),ownerName:db.users.find(x=>x.id===inv.ownerId)?.name||'Creator'});}
  if(method==='POST'&&p.startsWith('/api/invites/')&&p.endsWith('/accept')){const token=p.split('/')[3];const inv=db.invites.find(x=>x.token===token);if(!inv||inv.acceptedAt||Date.now()>inv.expiresAt)return json(res,404,{error:'Invite invalid or expired'});try{const b=await readJson(req);const email=inv.email;const name=String(b.name||'').trim();const password=String(b.password||'');let user=db.users.find(x=>x.email===email);if(user&&user.role!=='client')return json(res,409,{error:'Email belongs to a creator account'});if(user){if(!verify(password,user))return json(res,401,{error:'Incorrect password for your existing account'});}else{if(name.length<2||password.length<8)return json(res,400,{error:'Name and password (8+ chars) required'});const h=hash(password);user={id:id('user'),email,name,role:'client',passwordSalt:h.salt,passwordHash:h.hash,createdAt:now()};db.users.push(user);}if(!db.team.some(t=>t.ownerId===inv.ownerId&&t.memberUserId===user.id))db.team.push({id:id('team'),ownerId:inv.ownerId,memberUserId:user.id,role:'client',permissions:{projects:true,review:true,files:true,portfolio:false},createdAt:now()});inv.acceptedAt=now();save();return json(res,200,{user:publicUser(user)},{'Set-Cookie':sessionCookie(user.id)});}catch(e){return json(res,e.status||400,{error:e.message});}}

  m=p.match(/^\/api\/team(?:\/([^/]+))?$/);
  if(method==='GET'&&p==='/api/team'){if(!u||u.role!=='creator')return json(res,403,{error:'Creator only'});return json(res,200,db.team.filter(t=>t.ownerId===u.id).map(t=>({...t,user:publicUser(db.users.find(x=>x.id===t.memberUserId))})));}
  if(method==='PATCH'&&m&&m[1]){if(!u||u.role!=='creator')return json(res,403,{error:'Creator only'});const t=db.team.find(x=>x.id===m[1]&&x.ownerId===u.id);if(!t)return json(res,404,{error:'Not found'});const b=await readJson(req);t.permissions=Object.assign({},t.permissions,b.permissions||{});save();return json(res,200,t);}

  if(method==='GET'&&p==='/api/portfolio'){if(!u)return json(res,401,{error:'Unauthorized'});return json(res,200,db.portfolio.filter(x=>x.ownerId===u.id));}
  if(method==='POST'&&p==='/api/portfolio'){if(!u||u.role!=='creator')return json(res,403,{error:'Creator only'});const b=await readJson(req);const w={id:id('port'),ownerId:u.id,title:String(b.title||'Untitled').slice(0,120),type:String(b.type||'Project').slice(0,60),year:Number(b.year)||new Date().getFullYear(),description:String(b.description||'').slice(0,1000),coverColor:String(b.coverColor||'midnight'),public:b.public!==false,createdAt:now()};db.portfolio.push(w);save();return json(res,200,w);}
  m=p.match(/^\/api\/portfolio\/([^/]+)$/); if(method==='PATCH'&&m){if(!u||u.role!=='creator')return json(res,403,{error:'Creator only'});const w=db.portfolio.find(x=>x.id===m[1]&&x.ownerId===u.id);if(!w)return json(res,404,{error:'Not found'});const b=await readJson(req);Object.assign(w,{title:String(b.title??w.title).slice(0,120),type:String(b.type??w.type).slice(0,60),year:Number(b.year)||w.year,description:String(b.description??w.description).slice(0,1000),coverColor:String(b.coverColor??w.coverColor),public:b.public!==false});save();return json(res,200,w);}
  if(method==='DELETE'&&m){if(!u||u.role!=='creator')return json(res,403,{error:'Creator only'});const i=db.portfolio.findIndex(x=>x.id===m[1]&&x.ownerId===u.id);if(i<0)return json(res,404,{error:'Not found'});db.portfolio.splice(i,1);save();return json(res,200,{ok:true});}
  m=p.match(/^\/api\/public\/portfolio\/([^/]+)$/); if(method==='GET'&&m){const creator=db.users.find(x=>x.id===m[1]&&x.role==='creator');if(!creator)return json(res,404,{error:'Not found'});return json(res,200,{creator:{id:creator.id,name:creator.name},items:db.portfolio.filter(x=>x.ownerId===creator.id&&x.public)});}

  if(method==='GET'&&p==='/api/calendar'){if(!u)return json(res,401,{error:'Unauthorized'});return json(res,200,db.calendar.filter(e=>u.role==='creator'?e.ownerId===u.id:db.projects.some(pr=>pr.id===e.projectId&&pr.clientId===u.id)));}
  if(method==='POST'&&p==='/api/calendar'){if(!u||u.role!=='creator')return json(res,403,{error:'Creator only'});const b=await readJson(req);const t=linkTargets(u,{projectId:b.projectId});if(t.error)return json(res,400,{error:t.error});const ev={id:id('cal'),ownerId:u.id,projectId:t.projectId,title:String(b.title||'Event').slice(0,120),date:String(b.date||'').slice(0,20),time:String(b.time||'').slice(0,20),location:String(b.location||'').slice(0,180),notes:String(b.notes||'').slice(0,1000),createdAt:now()};db.calendar.push(ev);const pr=db.projects.find(x=>x.id===ev.projectId);if(pr?.clientId)notify(pr.clientId,'calendar','Schedule updated',`${ev.title} was added to ${pr.name}.`,pr.id);save();return json(res,200,ev);}
  m=p.match(/^\/api\/calendar\/([^/]+)$/); if(method==='DELETE'&&m){if(!u||u.role!=='creator')return json(res,403,{error:'Creator only'});const i=db.calendar.findIndex(x=>x.id===m[1]&&x.ownerId===u.id);if(i<0)return json(res,404,{error:'Not found'});db.calendar.splice(i,1);save();return json(res,200,{ok:true});}

  if(method==='GET'&&p==='/api/quotes'){if(!u)return json(res,401,{error:'Unauthorized'});return json(res,200,db.quotes.filter(q=>u.role==='creator'?q.ownerId===u.id:q.clientId===u.id));}
  if(method==='POST'&&p==='/api/quotes'){if(!u||u.role!=='creator')return json(res,403,{error:'Creator only'});const b=await readJson(req);const t=linkTargets(u,b);if(t.error)return json(res,400,{error:t.error});const items=Array.isArray(b.items)?b.items.map(x=>({description:String(x.description||'Item'),qty:Number(x.qty)||1,unit:Number(x.unit)||0})):[];const total=items.reduce((s,x)=>s+x.qty*x.unit,0);const q={id:id('quo'),ownerId:u.id,projectId:t.projectId,clientId:t.clientId,number:String(b.number||`Q-${new Date().getFullYear()}-${String(db.quotes.length+1).padStart(3,'0')}`),status:'Draft',currency:String(b.currency||'USD'),items,total,createdAt:now()};db.quotes.push(q);if(q.clientId)notify(q.clientId,'quote','New quote',`Quote ${q.number} is ready.`,q.projectId);save();return json(res,200,q);}
  m=p.match(/^\/api\/quotes\/([^/]+)$/); if(method==='PATCH'&&m){if(!u)return json(res,401,{error:'Unauthorized'});const q=db.quotes.find(x=>x.id===m[1]);if(!q)return json(res,404,{error:'Not found'});if(u.role==='creator'&&q.ownerId!==u.id)return json(res,403,{error:'Forbidden'});if(u.role==='client'&&q.clientId!==u.id)return json(res,403,{error:'Forbidden'});const b=await readJson(req);q.status=String(b.status||q.status);if(u.role==='client'&&['Accepted','Declined'].includes(q.status))notify(q.ownerId,'quote','Quote response',`${db.users.find(x=>x.id===u.id)?.name||'Client'} ${q.status.toLowerCase()} ${q.number}.`,q.projectId);save();return json(res,200,q);}

  if(method==='GET'&&p==='/api/invoices'){if(!u)return json(res,401,{error:'Unauthorized'});return json(res,200,db.invoices.filter(x=>u.role==='creator'?x.ownerId===u.id:x.clientId===u.id));}
  if(method==='POST'&&p==='/api/invoices'){if(!u||u.role!=='creator')return json(res,403,{error:'Creator only'});const b=await readJson(req);const t=linkTargets(u,b);if(t.error)return json(res,400,{error:t.error});const inv={id:id('inv'),ownerId:u.id,projectId:t.projectId,clientId:t.clientId,number:String(b.number||`INV-${new Date().getFullYear()}-${String(db.invoices.length+1).padStart(3,'0')}`),status:'Pending',currency:String(b.currency||'USD'),total:Number(b.total)||0,dueDate:String(b.dueDate||'').slice(0,20),createdAt:now()};db.invoices.push(inv);if(inv.clientId)notify(inv.clientId,'invoice','New invoice',`Invoice ${inv.number} is ready.`,inv.projectId);save();return json(res,200,inv);}
  m=p.match(/^\/api\/invoices\/([^/]+)$/); if(method==='PATCH'&&m){if(!u)return json(res,401,{error:'Unauthorized'});const inv=db.invoices.find(x=>x.id===m[1]);if(!inv)return json(res,404,{error:'Not found'});if(u.role==='creator'&&inv.ownerId!==u.id)return json(res,403,{error:'Forbidden'});if(u.role==='client'&&inv.clientId!==u.id)return json(res,403,{error:'Forbidden'});const b=await readJson(req);inv.status=String(b.status||inv.status);if(u.role==='client'&&inv.status==='Paid')notify(inv.ownerId,'invoice','Invoice paid',`${inv.number} is marked paid.`,inv.projectId);save();return json(res,200,inv);}

  if(method==='GET'&&p==='/api/contracts'){if(!u)return json(res,401,{error:'Unauthorized'});return json(res,200,db.contracts.filter(x=>u.role==='creator'?x.ownerId===u.id:x.clientId===u.id));}
  if(method==='POST'&&p==='/api/contracts'){if(!u||u.role!=='creator')return json(res,403,{error:'Creator only'});const b=await readJson(req);const t=linkTargets(u,b);if(t.error)return json(res,400,{error:t.error});const c={id:id('ctr'),ownerId:u.id,projectId:t.projectId,clientId:t.clientId,title:String(b.title||'Production Agreement').slice(0,160),status:'Pending Signature',content:String(b.content||'').slice(0,10000),createdAt:now()};db.contracts.push(c);if(c.clientId)notify(c.clientId,'contract','New contract',`${c.title} is ready for review.`,c.projectId);save();return json(res,200,c);}
  m=p.match(/^\/api\/contracts\/([^/]+)$/); if(method==='PATCH'&&m){if(!u)return json(res,401,{error:'Unauthorized'});const c=db.contracts.find(x=>x.id===m[1]);if(!c)return json(res,404,{error:'Not found'});if(u.role==='creator'&&c.ownerId!==u.id)return json(res,403,{error:'Forbidden'});if(u.role==='client'&&c.clientId!==u.id)return json(res,403,{error:'Forbidden'});const b=await readJson(req);if(u.role==='client'&&!['Signed','Changes Requested'].includes(b.status))return json(res,400,{error:'Invalid status'});c.status=String(b.status||c.status);if(u.role==='client')notify(c.ownerId,'contract','Contract response',`${u.name} updated ${c.title} to ${c.status}.`,c.projectId);save();return json(res,200,c);}

  if(method==='GET'&&p==='/api/notifications'){if(!u)return json(res,401,{error:'Unauthorized'});return json(res,200,db.notifications.filter(n=>n.userId===u.id));}
  m=p.match(/^\/api\/notifications\/([^/]+)$/); if(method==='PATCH'&&m){if(!u)return json(res,401,{error:'Unauthorized'});const n=db.notifications.find(x=>x.id===m[1]&&x.userId===u.id);if(!n)return json(res,404,{error:'Not found'});n.read=true;save();return json(res,200,n);}

  if(method==='POST'&&p==='/api/ai/production-plan'){if(!u)return json(res,401,{error:'Unauthorized'});try{const b=await readJson(req);const brief=String(b.brief||'').trim();if(!brief)return json(res,400,{error:'Brief required'});if(brief.length>4000)return json(res,400,{error:'Brief is too long (4000 characters max)'});if(ai.kind!=='baseline'&&!aiAllowed(u.id))return json(res,429,{error:'AI limit reached. Try again later.'});const out=await ai.plan(brief);const plan={id:id('ai'),ownerId:u.id,brief,source:out.source,model:out.model,createdAt:now(),result:out.result};db.aiPlans.unshift(plan);db.aiPlans=db.aiPlans.slice(0,1000);save();return json(res,200,plan);}catch(e){return json(res,e.status||400,{error:e.message});}}

  if(method==='GET'&&p.startsWith('/invite/')){const token=p.split('/')[2];res.writeHead(200,{...securityHeaders(),'Content-Type':'text/html; charset=utf-8'});return fs.createReadStream(path.join(PUBLIC,'invite.html')).pipe(res);}
  if(method==='GET'&&p.startsWith('/p/')){res.writeHead(200,{...securityHeaders(),'Content-Type':'text/html; charset=utf-8'});return fs.createReadStream(path.join(PUBLIC,'portfolio.html')).pipe(res);}

  const file=p==='/'?'index.html':p.replace(/^\//,'');const fp=path.normalize(path.join(PUBLIC,file));if(fp.startsWith(PUBLIC)&&fs.existsSync(fp)&&fs.statSync(fp).isFile()){res.writeHead(200,{...securityHeaders(),'Content-Type':mime(fp)});return fs.createReadStream(fp).pipe(res);}
  return text(res,404,'Not found');
}
function publicUser(u){if(!u)return null;return{id:u.id,email:u.email,name:u.name,role:u.role};}
async function main(){
  store=await openStore({empty,dbPath:DB_PATH});db=store.db;save=store.save;
  files=openFiles({uploadsDir:UPLOADS});mailer=openMailer();ai=openAI();
  seed();
  if(NODE_ENV==='production'){if(store.kind==='json')console.warn('Warning: DATABASE_URL is not set; data is stored in a local JSON file.');if(files.kind==='local')console.warn('Warning: STORAGE_BUCKET is not set; uploads are stored on local disk.');if(mailer.enabled&&!process.env.APP_BASE_URL)console.warn('Warning: APP_BASE_URL is not set; links in emails will point to localhost.');}
  console.log(`Integrations: database=${store.kind} storage=${files.kind} email=${mailer.enabled?'smtp':'off'} ai=${ai.kind}${ai.model?' ('+ai.model+')':''}`);
  const server=http.createServer((req,res)=>route(req,res).catch(e=>{console.error(e);if(!res.headersSent)json(res,e.status||500,{error:e.message||'Server error'});}));
  server.listen(PORT,()=>console.log(`CINESET running on http://localhost:${PORT}`));
  // Finish pending database writes before the host stops the process.
  for(const sig of ['SIGTERM','SIGINT'])process.once(sig,()=>{server.close();store.close().catch(e=>console.error(e.message)).finally(()=>process.exit(0));});
}
main().catch(e=>{console.error('CINESET failed to start:',e.message);process.exit(1);});
